// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sulglgujzroyqnmaoazr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1bGdsZ3VqenJveXFubWFvYXpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDc4ODAsImV4cCI6MjA2OTc4Mzg4MH0.AAt4fpDYcQfQYHz5pcIYaB3ucMlL43QPWcfU5ZIz9Bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});